import React, { useState, useEffect, useCallback } from 'react';
import axios from 'axios';

function ReportExport({ userId }) {
  const [assessments, setAssessments] = useState([]);
  const [userData, setUserData] = useState(null);
  const [loading, setLoading] = useState(true);

  const fetchData = useCallback(async () => {
    try {
      const [assessRes, userRes] = await Promise.all([
        axios.get(`http://localhost:5000/api/assessment/all/${userId}`),
        axios.get(`http://localhost:5000/api/user/${userId}`)
      ]);
      setAssessments(assessRes.data.assessments || []);
      setUserData(userRes.data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  }, [userId]);

  useEffect(() => {
    if (!userId) {
      setAssessments([]);
      setUserData(null);
      setLoading(false);
      return;
    }
    fetchData();
  }, [userId, fetchData]);

  const getSeverityColor = (s) => {
    if (s === 'SAM') return '#dc3545';
    if (s === 'MAM') return '#fd7e14';
    return '#28a745';
  };

  // PDF Print function
  const printReport = () => {
    window.print();
  };

  if (loading) return <div><h2>📄 Report</h2><p>⏳ Loading...</p></div>;

  const latest = assessments.length > 0 ? assessments[0] : null;

  return (
    <div style={{ background: 'white', padding: '25px', borderRadius: '12px', boxShadow: '0 2px 8px rgba(0,0,0,0.1)' }}>
      
      {/* Print Button (यह print में नहीं दिखेगा) */}
      <div className="no-print" style={{ marginBottom: '20px', textAlign: 'right' }}>
        <button onClick={printReport} style={{
          padding: '12px 30px', background: 'linear-gradient(135deg, #667eea, #764ba2)',
          color: 'white', border: 'none', borderRadius: '8px',
          cursor: 'pointer', fontSize: '16px', fontWeight: '600'
        }}>
          🖨️ Print / PDF Download करो
        </button>
      </div>

      {/* Report Header */}
      <div style={{
        textAlign: 'center', borderBottom: '3px solid #667eea',
        paddingBottom: '20px', marginBottom: '25px'
      }}>
        <h1 style={{ color: '#667eea', fontSize: '24px' }}>🏥 कुपोषण Detection Report</h1>
        <p style={{ color: '#666' }}>Malnutrition Screening Report - WHO Standards</p>
        <p style={{ color: '#999', fontSize: '13px' }}>
          Report Date: {new Date().toLocaleDateString('hi-IN')} | 
          Generated by: कुपोषण Detection System
        </p>
      </div>

      {/* Patient Info */}
      {userData && (
        <div style={{
          background: '#f8f9fa', padding: '20px',
          borderRadius: '8px', marginBottom: '20px',
          border: '1px solid #ddd'
        }}>
          <h3>👶 रोगी की जानकारी (Patient Information)</h3>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px', marginTop: '10px' }}>
            <p><strong>नाम:</strong> {userData.name}</p>
            <p><strong>फोन:</strong> {userData.phone}</p>
            <p><strong>उम्र:</strong> {userData.age} महीने</p>
            <p><strong>लिंग:</strong> {userData.gender === 'male' ? 'लड़का' : 'लड़की'}</p>
            <p><strong>स्थान:</strong> {userData.location}</p>
            <p><strong>User ID:</strong> {userData.id}</p>
          </div>
        </div>
      )}

      {/* Latest Assessment */}
      {latest && (
        <div style={{
          padding: '20px', borderRadius: '12px', marginBottom: '20px',
          border: `3px solid ${getSeverityColor(latest.severity)}`,
          background: latest.severity === 'SAM' ? '#f8d7da' :
                      latest.severity === 'MAM' ? '#fff3cd' : '#d4edda'
        }}>
          <h3>📊 Latest Assessment Result</h3>
          
          {/* Traffic Light */}
          <div style={{ textAlign: 'center', margin: '15px 0' }}>
            <div style={{
              display: 'inline-block', padding: '15px 40px',
              borderRadius: '25px', backgroundColor: getSeverityColor(latest.severity),
              color: 'white', fontSize: '22px', fontWeight: 'bold'
            }}>
              {latest.severity === 'SAM' && '🔴 SAM - गंभीर कुपोषण'}
              {latest.severity === 'MAM' && '🟠 MAM - मध्यम कुपोषण'}
              {latest.severity === 'NORMAL' && '🟢 NORMAL - सामान्य'}
            </div>
          </div>

          {/* Measurements */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '10px', marginTop: '15px' }}>
            <div style={{ background: 'white', padding: '12px', borderRadius: '8px', textAlign: 'center' }}>
              <p style={{ fontSize: '12px', color: '#666' }}>📏 Height</p>
              <p style={{ fontSize: '22px', fontWeight: 'bold' }}>{latest.height} cm</p>
            </div>
            <div style={{ background: 'white', padding: '12px', borderRadius: '8px', textAlign: 'center' }}>
              <p style={{ fontSize: '12px', color: '#666' }}>⚖️ Weight</p>
              <p style={{ fontSize: '22px', fontWeight: 'bold' }}>{latest.weight} kg</p>
            </div>
            <div style={{ background: 'white', padding: '12px', borderRadius: '8px', textAlign: 'center' }}>
              <p style={{ fontSize: '12px', color: '#666' }}>🔵 MUAC</p>
              <p style={{ fontSize: '22px', fontWeight: 'bold' }}>{latest.muac} cm</p>
            </div>
          </div>

          {/* Z-Scores */}
          <div style={{ marginTop: '15px' }}>
            <h4>📊 WHO Z-Scores:</h4>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '10px', marginTop: '10px' }}>
              <div style={{ background: 'white', padding: '12px', borderRadius: '8px', textAlign: 'center' }}>
                <p style={{ fontSize: '12px', color: '#666' }}>Weight-for-Age</p>
                <p style={{ fontSize: '20px', fontWeight: 'bold', color: latest.z_wfa < -2 ? '#dc3545' : '#28a745' }}>
                  {latest.z_wfa?.toFixed(2)}
                </p>
              </div>
              <div style={{ background: 'white', padding: '12px', borderRadius: '8px', textAlign: 'center' }}>
                <p style={{ fontSize: '12px', color: '#666' }}>Height-for-Age</p>
                <p style={{ fontSize: '20px', fontWeight: 'bold', color: latest.z_hfa < -2 ? '#dc3545' : '#28a745' }}>
                  {latest.z_hfa?.toFixed(2)}
                </p>
              </div>
              <div style={{ background: 'white', padding: '12px', borderRadius: '8px', textAlign: 'center' }}>
                <p style={{ fontSize: '12px', color: '#666' }}>Weight-for-Height</p>
                <p style={{ fontSize: '20px', fontWeight: 'bold', color: latest.z_wfh < -2 ? '#dc3545' : '#28a745' }}>
                  {latest.z_wfh?.toFixed(2)}
                </p>
              </div>
            </div>
          </div>

          {/* Additional */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px', marginTop: '15px' }}>
            <div style={{ background: 'white', padding: '12px', borderRadius: '8px', textAlign: 'center' }}>
              <p style={{ fontSize: '12px', color: '#666' }}>BMI</p>
              <p style={{ fontSize: '20px', fontWeight: 'bold' }}>{latest.bmi}</p>
            </div>
            <div style={{ background: 'white', padding: '12px', borderRadius: '8px', textAlign: 'center' }}>
              <p style={{ fontSize: '12px', color: '#666' }}>W/H Ratio</p>
              <p style={{ fontSize: '20px', fontWeight: 'bold' }}>{latest.wh_ratio}%</p>
            </div>
          </div>
        </div>
      )}

      {/* Assessment History */}
      {assessments.length > 0 && (
        <div style={{ marginBottom: '20px' }}>
          <h3>📋 Assessment History</h3>
          <table style={{
            width: '100%', borderCollapse: 'collapse',
            marginTop: '10px', fontSize: '13px'
          }}>
            <thead>
              <tr style={{ background: '#667eea', color: 'white' }}>
                <th style={{ padding: '10px' }}>Date</th>
                <th style={{ padding: '10px' }}>Height</th>
                <th style={{ padding: '10px' }}>Weight</th>
                <th style={{ padding: '10px' }}>MUAC</th>
                <th style={{ padding: '10px' }}>Z-WFH</th>
                <th style={{ padding: '10px' }}>Status</th>
              </tr>
            </thead>
            <tbody>
              {assessments.map((a, i) => (
                <tr key={i} style={{ borderBottom: '1px solid #ddd' }}>
                  <td style={{ padding: '8px', textAlign: 'center' }}>
                    {new Date(a.date).toLocaleDateString('hi-IN')}
                  </td>
                  <td style={{ padding: '8px', textAlign: 'center' }}>{a.height}</td>
                  <td style={{ padding: '8px', textAlign: 'center' }}>{a.weight}</td>
                  <td style={{ padding: '8px', textAlign: 'center' }}>{a.muac}</td>
                  <td style={{ padding: '8px', textAlign: 'center' }}>{a.z_wfh?.toFixed(2)}</td>
                  <td style={{
                    padding: '8px', textAlign: 'center', fontWeight: 'bold',
                    color: getSeverityColor(a.severity)
                  }}>{a.severity}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Z-Score Reference */}
      <div style={{
        background: '#f8f9fa', padding: '20px',
        borderRadius: '8px', marginBottom: '20px',
        borderLeft: '4px solid #667eea'
      }}>
        <h3>📚 WHO Z-Score Reference</h3>
        <p style={{ margin: '5px 0' }}>🟢 Z-Score &gt; -1: Normal (सामान्य)</p>
        <p style={{ margin: '5px 0' }}>🟡 Z-Score -1 to -2: Mild (हल्का कुपोषण)</p>
        <p style={{ margin: '5px 0' }}>🟠 Z-Score -2 to -3: MAM (मध्यम कुपोषण)</p>
        <p style={{ margin: '5px 0' }}>🔴 Z-Score &lt; -3: SAM (गंभीर कुपोषण)</p>
      </div>

      {/* Footer */}
      <div style={{
        textAlign: 'center', borderTop: '2px solid #ddd',
        paddingTop: '15px', color: '#999', fontSize: '12px'
      }}>
        <p>🏥 कुपोषण Detection System - National Level Hackathon Project</p>
        <p>Based on WHO Child Growth Standards | Made for Rural India</p>
        <p>Report generated on: {new Date().toLocaleString('hi-IN')}</p>
      </div>
    </div>
  );
}

export default ReportExport;